import { XSadd } from 'ml-xsadd';
import { expect, test } from 'vitest';

import { decode, encode } from '../index.ts';

import { allBytes, base64AllBytes, tests } from './data.ts';

const textEncoder = new TextEncoder();

test.each(tests)('%s -> %s', (base64, binary) => {
  const encodedBase64 = textEncoder.encode(base64);
  const encodedBinary = textEncoder.encode(binary);

  expect(Array.from(decode(encodedBase64))).toStrictEqual(
    Array.from(encodedBinary),
  );
});

test('All possibles values', () => {
  const encodeBase64 = textEncoder.encode(base64AllBytes);

  expect(Array.from(decode(encodeBase64))).toStrictEqual(Array.from(allBytes));
});

/**
 * Reproducible random bytes, so a failure can be replayed from its seed.
 * @param length - number of bytes to generate.
 * @param seed - seed for the generator.
 * @returns the generated bytes.
 */
function randomBytes(length: number, seed: number): Uint8Array {
  const generator = new XSadd(seed);
  const bytes = new Uint8Array(length);
  let i = 0;
  for (; i + 4 <= length; i += 4) {
    const value = generator.getUint32();
    bytes[i] = value;
    bytes[i + 1] = value >>> 8;
    bytes[i + 2] = value >>> 16;
    bytes[i + 3] = value >>> 24;
  }
  const tail = generator.getUint32();
  for (let shift = 0; i < length; i++, shift += 8) {
    bytes[i] = tail >>> shift;
  }
  return bytes;
}

// Sizes straddling the internal thresholds: the scalar tail, the batched
// 8-groups-per-iteration loop, and the native decoder's minimum length.
test.each([0, 1, 2, 3, 61, 62, 63, 64, 189, 255, 256, 257, 1023, 1024, 5000])(
  'round-trips %i bytes',
  (length) => {
    const bytes = randomBytes(length, length + 1);

    expect(Array.from(decode(encode(bytes)))).toStrictEqual(Array.from(bytes));
  },
);

// 600 bytes stay under the native decoder's minimum length and so exercise the
// scalar path; 3000 bytes go through the native one.
test.each([
  [0, 600],
  [1, 600],
  [2, 600],
  [3, 600],
  [5, 600],
  [6, 600],
  [7, 600],
  [0, 3000],
  [1, 3000],
  [2, 3000],
  [3, 3000],
  [5, 3000],
  [6, 3000],
  [7, 3000],
])('decodes a view at byteOffset %i of %i bytes', (offset, length) => {
  const bytes = randomBytes(length, offset + 1);
  const base64 = encode(bytes);
  const backing = new Uint8Array(base64.length + offset);
  backing.set(base64, offset);
  const view = backing.subarray(offset, offset + base64.length);

  expect(Array.from(decode(view))).toStrictEqual(Array.from(bytes));
});

test('accepts an ArrayBuffer', () => {
  const bytes = randomBytes(300, 7);
  const base64 = encode(bytes).slice();

  expect(
    Array.from(decode(base64.buffer as unknown as Uint8Array)),
  ).toStrictEqual(Array.from(bytes));
});

test('decodes an input larger than the native chunk size', () => {
  // 900000 bytes encode to 1200000 base64 bytes, past the 1 MB chunk boundary.
  const bytes = randomBytes(900000, 99);
  const decoded = decode(encode(bytes));

  let firstDifference = -1;
  for (let i = 0; i < bytes.length; i++) {
    if (decoded[i] !== bytes[i]) {
      firstDifference = i;
      break;
    }
  }

  expect(decoded).toHaveLength(900000);
  expect(firstDifference).toBe(-1);
});

test('falls back to the scalar path on invalid characters', () => {
  // '*' is not in the alphabet. The native decoder rejects it, so this must go
  // through the scalar path and reproduce the historical byte-for-byte result.
  const input = textEncoder.encode('QQ*='.repeat(512));
  const decoded = decode(input);

  expect(decoded).toHaveLength(1535);
  expect(Array.from(decoded.subarray(0, 6))).toStrictEqual([
    65, 63, 192, 65, 63, 192,
  ]);
});

test('the returned view keeps the padded buffer of the original', () => {
  const oneMissingOctet = decode(textEncoder.encode('QQQ='));
  const twoMissingOctets = decode(textEncoder.encode('QQ=='));

  expect(oneMissingOctet).toHaveLength(2);
  expect(oneMissingOctet.buffer.byteLength).toBe(3);
  expect(twoMissingOctets).toHaveLength(1);
  expect(twoMissingOctets.buffer.byteLength).toBe(3);
});

test('throws when the length is not a multiple of 4', () => {
  expect(() => decode(new Uint8Array(3))).toThrow(
    'Unable to parse base64 string.',
  );
});

// An invalid character makes the native decoder decline, so these reach the
// scalar loop.
test.each([0, 1, 2, 3, 5, 6, 7])(
  'decodes an invalid view at byteOffset %i through the scalar path',
  (offset) => {
    const base64 = textEncoder.encode('QQ*='.repeat(600));
    const backing = new Uint8Array(base64.length + offset);
    backing.set(base64, offset);
    const view = backing.subarray(offset, offset + base64.length);
    const expected = decode(base64);

    expect(Array.from(decode(view))).toStrictEqual(Array.from(expected));
  },
);

test('keeps using the native decoder after a declined input', () => {
  const invalid = textEncoder.encode('QQ*='.repeat(600));
  const bytes = randomBytes(4000, 5);
  const base64 = encode(bytes);

  // The decline arms a backoff; every later call must still be correct, whether
  // it is served by the scalar path or, once the backoff lapses, natively.
  decode(invalid);
  for (let i = 0; i < 40; i++) {
    expect(Array.from(decode(base64))).toStrictEqual(Array.from(bytes));
  }
});
